/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TokenValidatorInterface extends ethers.utils.Interface {
  functions: {
    "JAMM_Token()": FunctionFragment;
    "batchValidate(address[],address[],uint256)": FunctionFragment;
    "checkValidation()": FunctionFragment;
    "factoryV1()": FunctionFragment;
    "panaromaswapV1Call(address,uint256,uint256,bytes)": FunctionFragment;
    "positionManager()": FunctionFragment;
    "refWalletFactory()": FunctionFragment;
    "validate(address,address[],uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "JAMM_Token",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchValidate",
    values: [string[], string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkValidation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factoryV1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "panaromaswapV1Call",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "positionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refWalletFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validate",
    values: [string, string[], BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "JAMM_Token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchValidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factoryV1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "panaromaswapV1Call",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "positionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refWalletFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validate", data: BytesLike): Result;

  events: {};
}

export class TokenValidator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TokenValidatorInterface;

  functions: {
    JAMM_Token(overrides?: CallOverrides): Promise<[string]>;

    batchValidate(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    checkValidation(overrides?: CallOverrides): Promise<[string]>;

    factoryV1(overrides?: CallOverrides): Promise<[string]>;

    panaromaswapV1Call(
      arg0: string,
      amount0: BigNumberish,
      arg2: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    positionManager(overrides?: CallOverrides): Promise<[string]>;

    refWalletFactory(overrides?: CallOverrides): Promise<[string]>;

    validate(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  JAMM_Token(overrides?: CallOverrides): Promise<string>;

  batchValidate(
    tokens: string[],
    baseTokens: string[],
    amountToBorrow: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  checkValidation(overrides?: CallOverrides): Promise<string>;

  factoryV1(overrides?: CallOverrides): Promise<string>;

  panaromaswapV1Call(
    arg0: string,
    amount0: BigNumberish,
    arg2: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  positionManager(overrides?: CallOverrides): Promise<string>;

  refWalletFactory(overrides?: CallOverrides): Promise<string>;

  validate(
    token: string,
    baseTokens: string[],
    amountToBorrow: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    JAMM_Token(overrides?: CallOverrides): Promise<string>;

    batchValidate(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number[]>;

    checkValidation(overrides?: CallOverrides): Promise<string>;

    factoryV1(overrides?: CallOverrides): Promise<string>;

    panaromaswapV1Call(
      arg0: string,
      amount0: BigNumberish,
      arg2: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    positionManager(overrides?: CallOverrides): Promise<string>;

    refWalletFactory(overrides?: CallOverrides): Promise<string>;

    validate(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {};

  estimateGas: {
    JAMM_Token(overrides?: CallOverrides): Promise<BigNumber>;

    batchValidate(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    checkValidation(overrides?: CallOverrides): Promise<BigNumber>;

    factoryV1(overrides?: CallOverrides): Promise<BigNumber>;

    panaromaswapV1Call(
      arg0: string,
      amount0: BigNumberish,
      arg2: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    positionManager(overrides?: CallOverrides): Promise<BigNumber>;

    refWalletFactory(overrides?: CallOverrides): Promise<BigNumber>;

    validate(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    JAMM_Token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    batchValidate(
      tokens: string[],
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    checkValidation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    factoryV1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    panaromaswapV1Call(
      arg0: string,
      amount0: BigNumberish,
      arg2: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    positionManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    refWalletFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    validate(
      token: string,
      baseTokens: string[],
      amountToBorrow: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
