/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPanaromaswapV2edgeMintCallback,
  IPanaromaswapV2edgeMintCallbackInterface,
} from "../IPanaromaswapV2edgeMintCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount0Owed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1Owed",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "panaromaswapV2edgeMintCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPanaromaswapV2edgeMintCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPanaromaswapV2edgeMintCallbackInterface {
    return new utils.Interface(
      _abi
    ) as IPanaromaswapV2edgeMintCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPanaromaswapV2edgeMintCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPanaromaswapV2edgeMintCallback;
  }
}
