/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPanaromaswapV2edgePoolDeployer,
  IPanaromaswapV2edgePoolDeployerInterface,
} from "../IPanaromaswapV2edgePoolDeployer";

const _abi = [
  {
    inputs: [],
    name: "parameters",
    outputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
      {
        internalType: "int24",
        name: "tickSpacing",
        type: "int24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPanaromaswapV2edgePoolDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IPanaromaswapV2edgePoolDeployerInterface {
    return new utils.Interface(
      _abi
    ) as IPanaromaswapV2edgePoolDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPanaromaswapV2edgePoolDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPanaromaswapV2edgePoolDeployer;
  }
}
