/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPanaromaswapV2edgeSwapCallback,
  IPanaromaswapV2edgeSwapCallbackInterface,
} from "../IPanaromaswapV2edgeSwapCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "amount0Delta",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "amount1Delta",
        type: "int256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "panaromaswapV2edgeSwapCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPanaromaswapV2edgeSwapCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPanaromaswapV2edgeSwapCallbackInterface {
    return new utils.Interface(
      _abi
    ) as IPanaromaswapV2edgeSwapCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPanaromaswapV2edgeSwapCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPanaromaswapV2edgeSwapCallback;
  }
}
