/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPanaromaswapV2edgeFlashCallback,
  IPanaromaswapV2edgeFlashCallbackInterface,
} from "../IPanaromaswapV2edgeFlashCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fee0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "fee1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "panaromaswapV2edgeFlashCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPanaromaswapV2edgeFlashCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPanaromaswapV2edgeFlashCallbackInterface {
    return new utils.Interface(
      _abi
    ) as IPanaromaswapV2edgeFlashCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPanaromaswapV2edgeFlashCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPanaromaswapV2edgeFlashCallback;
  }
}
