/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IrefWalletFactory,
  IrefWalletFactoryInterface,
} from "../IrefWalletFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "getUserInfo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IrefWalletFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IrefWalletFactoryInterface {
    return new utils.Interface(_abi) as IrefWalletFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IrefWalletFactory {
    return new Contract(address, _abi, signerOrProvider) as IrefWalletFactory;
  }
}
