/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IvalidationStorageFactory,
  IvalidationStorageFactoryInterface,
} from "../IvalidationStorageFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "getUserInfo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IvalidationStorageFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IvalidationStorageFactoryInterface {
    return new utils.Interface(_abi) as IvalidationStorageFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IvalidationStorageFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IvalidationStorageFactory;
  }
}
