/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IvalidationStorage,
  IvalidationStorageInterface,
} from "../IvalidationStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "checkAnalysis",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "string",
        name: "",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IvalidationStorage__factory {
  static readonly abi = _abi;
  static createInterface(): IvalidationStorageInterface {
    return new utils.Interface(_abi) as IvalidationStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IvalidationStorage {
    return new Contract(address, _abi, signerOrProvider) as IvalidationStorage;
  }
}
